site_name: MetaVision2 Docs
site_author: Vision AI Ops Team
site_description: 기존에 관리되지 않고 있는 데이터에 대한 관리 커버리지 및 재활용성을 높이고, CVPaaS Cloud 서비스에서의 확장성 있고 비용 효율적인 AI Ops 서비스의 기반을 제공하여, Golden Data Discovery & AI 모델 개선 Cycle을 완성하기 위한 플랫폼

site_url: https://mnms.github.io/metavision2_docs
copyright: All right reserved, <a href='https://metavision.io'>Vision AI Ops Team</a>.


repo_name: source repository
repo_url: https://github.com/mnms/metavision2_docs

nav:
  - Introduction:
    - Overview: index.md

  - Storage & Database:
    - Data Lake: data_lake.md
    - Data Warehouse: data_warehouse.md

  - Management:
    - Dashboard: dashboard.md
    - ML Workflow & Event: workflow_event.md


plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 0.1
